# Generated by Django 4.1.1 on 2022-12-07 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anteproyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('a_nombre', models.CharField(max_length=300)),
                ('tipoProyecto', models.CharField(choices=[('PROPUESTA PROPIA', 'PROPUESTA PROPIA'), ('BANCO DE PROYECTOS', 'BANCO DE PROYECTOS'), ('TRABAJADOR', 'TRABAJADOR')], default='PROPUESTA PROPIA', max_length=25)),
                ('fechaEntrega', models.DateTimeField(auto_now_add=True)),
                ('numIntegrantes', models.IntegerField(default=1)),
                ('estatus', models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15)),
                ('estatusR1', models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15)),
                ('estatusR2', models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15)),
                ('codigoUnion', models.CharField(blank=True, max_length=10, null=True)),
                ('periodoInicio', models.DateField(default=datetime.date.today, null=True)),
                ('periodoFin', models.DateField(null=True)),
                ('anteproyectoDoc', models.FileField(blank=True, null=True, upload_to='records/anteproyectoDoc/')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorExterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('d_nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('giro', models.CharField(blank=True, choices=[('INDUSTRIAL', 'INDUSTRIAL'), ('SERVICIOS', 'SERVICIOS'), ('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO'), ('OTRO', 'OTRO')], default='PUBLICO', max_length=20)),
                ('numCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(blank=True, max_length=200, null=True)),
                ('mision', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('numCelular', models.CharField(blank=True, max_length=20, null=True)),
                ('correoElectronico', models.CharField(blank=True, max_length=200, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('VACACIONES', 'VACIONES'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15)),
                ('puesto', models.CharField(blank=True, max_length=70, null=True)),
                ('fotoUsuario', models.ImageField(blank=True, default='profilepicD.jpg', null=True, upload_to='profilesPic/teachers/')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('municipio', models.CharField(blank=True, max_length=200, null=True)),
                ('codigoPostal', models.CharField(blank=True, max_length=5, null=True)),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de Mexico', 'Estado de Mexico'), ('Michoacan', 'Michoacan'), ('Morelos', 'Michoacan'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo Leon'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro', 'Queretaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosi', 'San Luis Potosi'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatan'), ('Zacatecas', 'Zacatecas')], default='Oaxaca', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('clave', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('semestre', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('fechaCreacion', models.DateField(default=datetime.date.today)),
                ('incrementarDias', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('rf_hojaRevisores', models.FileField(blank=True, null=True, upload_to='records/reporteF/hojaRevisores/')),
                ('rf_formatoEvaluacion', models.FileField(blank=True, null=True, upload_to='records/reporteF/formatoEvaluacion/')),
                ('rf_fechaEntrega', models.DateField(default=datetime.date.today, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteParcial1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('r1_hojaRevisores', models.FileField(blank=True, null=True, upload_to='records/reporte1/hojaRevisores/')),
                ('r1_formatoEvaluacion', models.FileField(blank=True, null=True, upload_to='records/reporte1/formatoEvaluacion/')),
                ('r1_fechaEntrega', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteParcial2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('r2_hojaRevisores', models.FileField(blank=True, null=True, upload_to='records/reporte2/hojaRevisores/')),
                ('r2_formatoEvaluacion', models.FileField(blank=True, null=True, upload_to='records/reporte2/formatoEvaluacion/')),
                ('r2_fechaEntrega', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitularDependencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('t_nombre', models.CharField(max_length=100)),
                ('t_apellidoP', models.CharField(max_length=70)),
                ('t_apellidoM', models.CharField(max_length=70)),
                ('t_puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('tipoProyecto', models.CharField(choices=[('PROPUESTA PROPIA', 'PROPUESTA PROPIA'), ('BANCO DE PROYECTOS', 'BANCO DE PROYECTOS'), ('TRABAJADOR', 'TRABAJADOR')], max_length=25)),
                ('numIntegrantes', models.IntegerField(default=1)),
                ('estatus', models.CharField(blank=True, choices=[('INICIADA', 'INICIADA'), ('EN PROCESO', 'EN PROCESO'), ('PROROGA', 'PROROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA')], default='INICIADA', max_length=15)),
                ('periodoInicio', models.DateField(null=True)),
                ('periodoFin', models.DateField(null=True)),
                ('asesorExterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.asesorexterno')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia')),
                ('r_asesorInterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_asesorInterno', to='Accounts.docente')),
                ('r_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_revisor', to='Accounts.docente')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('materias', models.ManyToManyField(blank=True, to='Accounts.materia')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('observacionD', models.CharField(blank=True, max_length=3000, null=True)),
                ('fechaElaboracion', models.DateField(default=datetime.date.today)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.docente')),
                ('observacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacion')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('estatus', models.CharField(blank=True, choices=[('INICIAL', 'INICIAL'), ('PROCESO', 'PROCESO'), ('COMPLETO', 'COMPLETO')], default='INICIAL', max_length=15)),
                ('solicitudResidencia', models.FileField(blank=True, null=True, upload_to='records/solicitudResidencia/')),
                ('anteproyecto', models.FileField(blank=True, null=True, upload_to='records/anteproyectoAceptado/')),
                ('dictamen', models.FileField(blank=True, null=True, upload_to='records/dictamen/')),
                ('horario', models.FileField(blank=True, null=True, upload_to='records/horario/')),
                ('cartaCompromiso', models.FileField(blank=True, null=True, upload_to='records/cartaC/')),
                ('cronograma', models.FileField(blank=True, null=True, upload_to='records/crono/')),
                ('cartaPresentacion', models.FileField(blank=True, null=True, upload_to='records/cartaP/')),
                ('cartaAceptacion', models.FileField(blank=True, null=True, upload_to='records/cartaAceptacion/')),
                ('cartaLiberacion', models.FileField(blank=True, null=True, upload_to='records/cartaLiberacion/')),
                ('manualUsuario', models.FileField(blank=True, null=True, upload_to='records/manualUsuario/')),
                ('manualTecnico', models.FileField(blank=True, null=True, upload_to='records/manualTecnico/')),
                ('reporteFinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reportefinal')),
                ('reporteParcial1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reporteparcial1')),
                ('reporteParcial2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reporteparcial2')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('numCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(blank=True, max_length=200, null=True)),
                ('numControl', models.CharField(blank=True, error_messages={'unique': 'Existe otro alumno con este numero de control.'}, max_length=8, unique=True)),
                ('carrera', models.CharField(choices=[('Ingenieria Sistemas Computacionales', 'Ingenieria Sistemas Computacionales'), ('Ingenieria Civil', 'Ingenieria Civil'), ('Ingenieria Industrial', 'Ingenieria Industrial')], default='Ingenieria Sistemas Computacionales', max_length=200)),
                ('semestre', models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')])),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('institutoSeguridadSocial', models.CharField(blank=True, max_length=200)),
                ('numSeguridadSocial', models.CharField(blank=True, max_length=70, null=True)),
                ('fotoUsuario', models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='profilesPic/students/')),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto')),
                ('domicilio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.domicilio')),
                ('expediente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.expediente')),
                ('residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.residencia')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='perfilAcademico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.perfilacademico'),
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='domicilio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.domicilio'),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='titular',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.titulardependencia'),
        ),
        migrations.AddField(
            model_name='asesorexterno',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia'),
        ),
        migrations.CreateModel(
            name='Anteproyecto_materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('compatibilidad', models.IntegerField(blank=True, null=True)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.materia')),
            ],
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='asesorExterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.asesorexterno'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='observacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.observacion'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='revisor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor1', to='Accounts.docente'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='revisor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor2', to='Accounts.docente'),
        ),
    ]
