# Generated by Django 4.1.1 on 2022-12-07 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='periodoFin',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='periodoInicio',
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='fechaEntrega',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
