# Generated by Django 4.1.1 on 2022-12-12 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_anteproyecto_periodofin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='anteproyectoDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/anteproyectoDoc/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
