# Generated by Django 4.1.1 on 2022-12-12 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_anteproyecto_anteproyectodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='anteproyecto',
            field=models.FileField(blank=True, null=True, upload_to='records/anteproyectoAceptado/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaAceptacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaAceptacion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaCompromiso',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaC/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaLiberacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaLiberacion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaPresentacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaP/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cronograma',
            field=models.FileField(blank=True, null=True, upload_to='records/crono/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dictamen',
            field=models.FileField(blank=True, null=True, upload_to='records/dictamen/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='horario',
            field=models.FileField(blank=True, null=True, upload_to='records/horario/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='manualTecnico',
            field=models.FileField(blank=True, null=True, upload_to='records/manualTecnico/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='manualUsuario',
            field=models.FileField(blank=True, null=True, upload_to='records/manualUsuario/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='solicitudResidencia',
            field=models.FileField(blank=True, null=True, upload_to='records/solicitudResidencia/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reportefinal',
            name='rf_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporteF/formatoEvaluacion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reportefinal',
            name='rf_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporteF/hojaRevisores/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='r1_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte1/formatoEvaluacion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='r1_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte1/hojaRevisores/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='r2_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte2/formatoEvaluacion/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='r2_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte2/hojaRevisores/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
