# Generated by Django 4.1.1 on 2022-12-12 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_expediente_anteproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='anteproyectoDoc',
            field=models.FileField(default=None, upload_to='records/anteproyectoDoc/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
