# Generated by Django 4.1.1 on 2022-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_anteproyecto_anteproyectodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatusR1',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatusR2',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15),
        ),
    ]
