# Generated by Django 4.1.1 on 2023-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_anteproyecto_estatusr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estatus',
            field=models.CharField(choices=[('INICIAL', 'INICIAL'), ('PROCESO', 'PROCESO'), ('COMPLETO', 'COMPLETO'), ('FINALIZADO', 'FINALIZADO')], default='INICIAL', max_length=15),
        ),
    ]
