# Generated by Django 4.1.1 on 2023-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_expediente_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='numIntegrantes',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
    ]
