# Generated by Django 4.1.1 on 2023-01-04 03:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_anteproyecto_numintegrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='estatus',
            field=models.CharField(blank=True, choices=[('INICIADA', 'INICIADA'), ('EN PROCESO', 'EN PROCESO'), ('PRORROGA', 'PRORROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA')], default='INICIADA', max_length=15),
        ),
        migrations.CreateModel(
            name='Actualizacion_anteproyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto')),
            ],
        ),
    ]
