# Generated by Django 4.1.1 on 2023-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_residencia_estatus_actualizacion_anteproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion_anteproyecto',
            name='estado',
            field=models.CharField(choices=[('NO LEIDO', 'NO LEIDO'), ('LEIDO', 'LEIDO')], default='NO LEIDO', max_length=10),
            preserve_default=False,
        ),
    ]
