# Generated by Django 4.1.1 on 2023-01-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_actualizacion_anteproyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion_anteproyecto',
            name='estado',
            field=models.CharField(choices=[('NO LEIDO', 'NO LEIDO'), ('LEIDO', 'LEIDO')], default='NO LEIDO', max_length=10),
        ),
    ]
