# Generated by Django 4.1.1 on 2023-01-05 01:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_observaciondocente_fechaelaboracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(choices=[('ESTUDIANTES', 'ESTUDIANTES'), ('DOCENTES', 'DOCENTES'), ('TODOS', 'TODOS'), ('PRIVADO', 'PRIVADO')], default='TODOS', max_length=200)),
                ('tiempoVida', models.PositiveIntegerField(default=0)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('docente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.docente')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.estudiante')),
            ],
        ),
    ]
