# Generated by Django 4.1.1 on 2023-01-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_avisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='entidad',
            field=models.CharField(choices=[('ESTUDIANTES', 'ESTUDIANTES'), ('DOCENTES', 'DOCENTES'), ('TODOS', 'TODOS')], default='TODOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='avisos',
            name='tiempoVida',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
