# Generated by Django 4.1.1 on 2023-01-05 05:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_alter_avisos_entidad_alter_avisos_tiempovida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
