# Generated by Django 4.1.1 on 2023-01-05 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_alter_avisos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciondocente',
            name='observacionD',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
