# Generated by Django 4.1.1 on 2023-01-05 20:28

import Apps.Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_alter_observaciondocente_observaciond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='tiempoVida',
            field=models.PositiveIntegerField(default=1, validators=[Apps.Accounts.models.validate_nonzero]),
        ),
    ]
