# Generated by Django 4.1.1 on 2023-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_alter_avisos_tiempovida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos',
            name='entidad',
            field=models.CharField(choices=[('ESTUDIANTES', 'ESTUDIANTES'), ('DOCENTES', 'DOCENTES'), ('TODOS', 'TODOS'), ('PRIVADO', 'PRIVADO')], default='TODOS', max_length=20),
        ),
    ]
