# Generated by Django 4.1.1 on 2023-01-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_avisos_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisos',
            name='visible',
        ),
    ]
