# Generated by Django 4.1.1 on 2023-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_alter_avisos_docente_alter_avisos_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('VACACIONES', 'VACIONES'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15),
        ),
    ]
