# Generated by Django 4.1.1 on 2023-01-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_alter_docente_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
