# Generated by Django 4.1.1 on 2023-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_alter_materia_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
