# Generated by Django 4.1.1 on 2023-01-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_alter_materia_clave_alter_materia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(error_messages={'unique': 'Existe otro materia con esta clave.'}, max_length=10, null=True, unique=True),
        ),
    ]
