# Generated by Django 4.1.1 on 2023-01-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_alter_dependencia_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numControl',
            field=models.CharField(blank=True, error_messages={'unique': 'Existe otro alumno con este numero de control.'}, max_length=10, unique=True),
        ),
    ]
