# Generated by Django 4.1.1 on 2023-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_alter_estudiante_numcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correoElectronico',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
