# Generated by Django 4.1.1 on 2023-01-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_alter_estudiante_correoelectronico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='anteproyecto',
        ),
        migrations.CreateModel(
            name='Estudiante_Anteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.estudiante')),
            ],
        ),
    ]
