# Generated by Django 4.1.1 on 2023-01-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0032_remove_estudiante_residencia_estudiante_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatus',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO'), ('CANCELADO', 'CANCELADO')], default='ENVIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='estatus',
            field=models.CharField(blank=True, choices=[('INICIADA', 'INICIADA'), ('EN PROCESO', 'EN PROCESO'), ('PRORROGA', 'PRORROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA'), ('CANCELADA', 'CANCELADA')], default='INICIADA', max_length=15),
        ),
    ]
