# Generated by Django 4.1.1 on 2023-01-25 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_alter_estudiante_correoelectronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyViewModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('a_nombre', models.CharField(max_length=300)),
                ('estatus', models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO'), ('CANCELADO', 'CANCELADO')], default='ENVIADO', max_length=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15)),
            ],
            options={
                'db_table': 'testView',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='semestre',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=8),
        ),
    ]
