# Generated by Django 4.1.1 on 2023-01-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_myviewmodel_alter_estudiante_semestre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myviewmodel',
            table='testview',
        ),
    ]
