# Generated by Django 4.1.1 on 2023-02-01 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_alter_myviewmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante_Autorizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=150, null=True)),
                ('num_control', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='semestre',
            field=models.IntegerField(choices=[(9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=8),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='estatus',
            field=models.CharField(choices=[('INICIADA', 'INICIADA'), ('EN PROCESO', 'EN PROCESO'), ('PRORROGA', 'PRORROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA'), ('CANCELADA', 'CANCELADA')], default='INICIADA', max_length=15),
        ),
    ]
