# Generated by Django 4.1.1 on 2023-02-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_estudiante_autorizado_alter_estudiante_semestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante_autorizado',
            name='is_registrado',
            field=models.BooleanField(default=False),
        ),
    ]
