# Generated by Django 4.1.1 on 2023-02-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0041_invitacion_fecha_elaboracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='estudiante_remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.estudiante'),
        ),
    ]
