# Generated by Django 4.1.1 on 2023-02-05 14:18

import Apps.Accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0042_alter_invitacion_anteproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='anteproyectoDoc',
            field=models.FileField(default=None, upload_to='records/anteproyectoDoc/', validators=[django.core.validators.FileExtensionValidator(['pdf']), Apps.Accounts.validators.validate_file_size]),
        ),
    ]
